### ISSUE TITLE
RFC: Code styling

### ISSUE THREAD

**Issue by asleep-cult** [HuyaneMatsu/scarletio#5]
## Warning
You're gonna hate this issue 🅰️ 

## Introduction
Scarletio (and Hata) use an unorthodox code style that may be intimidating to contributors and users. I've decided to make this issue in an attempt to create a code styling convention that would be enforced throughout this codebase. A cleaner styling convention would increase readability and maintainability tenfold. I am willing refactor the codebase to implement a new coding style.

## Imports
I propose that imports be sorted alphabetically, this can be done automatically by tools like isort.

## Line Continuations
Scarletio uses line continuations to break imports into multiple lines. I propose that all occurrences of line continuations be replaced by parenthesis.

Example:
```py
from a import a, b, \
    c, d, e, f, g
```
becomes
```py
from a import (
    a, b, c, d, e, f, g
)
```

## Whitespace
Scarletio uses lots of unnecessary whitespace on blank lines and in-between function definitions in classes. In other areas is doesn't use enough whitespace. I propose that a flake8 compatible whitespace convention be adopted.
Note: This would also entail removing unnecessary indents from blank lines.

Example:
```py
from math import log

MAGIC_NUMBER = 0x5f3759df
    
class Mathematician:
    def __init__(self, name):
        self.name = name
    
    
    def q_sqrt(self, x):
        # Definitely a real working Q_sqrt implementation.
        return MAGIC_NUMBER-(x>>1)
```
becomes
```py
from math import log

MAGIC_NUMBER = 0x5f3759df


class Mathematician:
    def __init__(self, name):
        self.name = name

    def q_sqrt(self, x):
        # Definitely a real working Q_sqrt implementation.
        return MAGIC_NUMBER - (x >> 1)
```

## Parenthesis
Scarletio uses some unnecessary parenthesis in if statements. I propose that these unnecessary parenthesis be removed and that the end of multiline parenthesis be moved to match the indentation level.

Example:
```py
if (not isinstance(x, ABC)) or (not isinstance(y, XYZ)):
    raise TypeError('received invalid x'
        'or invalid y')
```
becomes
```py
if not isinstance(x, ABC) or not isinstance(y, XYZ):
    raise TypeError(
        'received invalid x or invalid y'
    )
 ```
 
 ## Stdlib (not really style)
 Scarletio reimplements some things that already exists in stdlib. I propose that such modules be deleted and that the stdlib modules be used instead.

Example:
```py
print(code.CO_OPTIMIZED)
assert async_utils.is_coroutine_funciton(x)
print(utils.relative_index(y))
```
becomes
```py
import inspect
import bisect

print(inspect.CO_OPTIMIZED)
assert inspect.iscoroutinefunction(x)
print(bisect.bisect(y))
```

**Comment by HuyaneMatsu** [comment]
![Screenshot from 2021-12-18 07-13-17](https://user-images.githubusercontent.com/37266847/146631466-661c872f-53f7-433b-82b4-dcc28629634c.png)

**Comment by HuyaneMatsu** [comment]
### Warning

Contains memes (and typos)

### Response

> Scarletio uses line continuations to break imports into multiple lines. I propose that all occurrences of line continuations be replaced by parenthesis.

Imports contain no code logic, meaning if someone opens a file, they just ignore it, because it is useless information.

Example:
```
You want to check the code inside of a file.
You open it:
- 50 line long license
- 200 lines of imports
```

Breaking the imports like:
```py
from a import (
    a, b, c, d, e, f, g
)
```
Is still way better than
```py
from a import (
    a,
    b,
    c,
    d,
    e,
    f,
    g,
)
```
The only problem with your example comes in when we talk about high-line lengths. Scarletio uses 120 character long lines if applicable, leaving a lot of empty space.

> Scarletio uses lots of unnecessary whitespace on blank lines and in-between function definitions in classes. In other areas is doesn't use enough whitespace. I propose that a flake8 compatible whitespace convention be adopted.
Note: This would also entail removing unnecessary indents from blank lines.

White space on blank lines helps in editing the code. It is not related to readability. People probably do too much #nocode, that is how they never met this problem.

Adding white space between operations is a really questionable topic. Even the style guides contradiction themselves.

```py
# good
i = i + 1
# wrong
hypot2 = x * x + y * y
c = (a + b) * (a - b)
```

> Scarletio uses some unnecessary parenthesis in if statements. I propose that these unnecessary parenthesis be removed

Parentheses increase `if` statement readability. The famous `not` keyword makes the logic unreadable. I propose the usage of `!` instead.

> and that the end of multiline parenthesis be moved to match the indentation level.

That is just some leftover code. New exceptions are usually styled as in your example.

> Scarletio reimplements some things that already exists in stdlib. I propose that such modules be deleted and that the stdlib modules be used instead.

When I implemented some, I just didn't know they exist (`bisect.bisect`). At other cases, they are just too unoptimized (`inspect.iscoroutinefunction` <- also bad naming practice, consider opening an issue to fix names in stdlib?).

**Comment by HuyaneMatsu** [comment]
## Warning

You're gonna hate this answer 🅰️ 

## Conclusion

If you write your own code formatter, I will accept your request.

**Comment by asleep-cult** [comment]
challenge accepted (although it may take a year or two).
